### ISSUE TITLE
Multiple channels?

### ISSUE THREAD

**Issue by jamen** [audiojs/audio-oscillator#2]
How would you do something like using two oscillators for each channel?  Some other component to combined?

**Comment by dy** [comment]
Good call.
You can pass `channels: 2` to options, but that will produce same signal in each channel.
Yeah, I guess we should have [audio-splitter](https://developer.mozilla.org/en-US/docs/Web/API/ChannelSplitterNode) and [audio-merger](https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode) modules for that, an ideas for packages.

**Comment by jamen** [comment]
https://github.com/audiojs/contributing/issues/3
